
def getQuestReqs():

    questDic = {}

    questDic["Aftermath"] = ["Twilight of the Gods"],
    questDic["All Fired Up"] = ["Priest in Peril"],
    questDic["Alpha vs Omega"] = ["Remains of the Necrolord", "Misc:30,000 City of Um vessel souls"],
    questDic["Animal Magnetism"] = ["The Restless Ghost", "Ernest the Chicken", "Priest in Peril",
                                    "Misc:Ability to enter Morytania"],
    questDic["Another Slice of H.A.M."] = ["Death to the Dorgeshuun", "The Dig Site", "The Giant Dwarf"],
    questDic["As a First Resort"] = ["Zogre Flesh Eaters"],
    questDic["Azzanadra's Quest"] = ["The Vault of Shadows", "Raksha, the Shadow Colossus (quest)", "Desperate Creatures"],
    questDic["Back to my Roots"] = ["A Fairy Tale I - Growing Pains", "The Hand in the Sand", "One Small Favour",
                                    "Tribal Totem"],
    questDic["Back to the Freezer"] = ["Some Like It Cold", "Ernest the Chicken"],
    questDic["Bar Crawl (miniquest)"] = [],
    questDic["Battle of the Monolith"] = ["Azzanadra's Quest"],
    questDic["Follows:Battle of the Monolith"] = ["The Brink of Extinction"],
    questDic["Beneath Cursed Tides"] = [],
    questDic["Benedict's World Tour (miniquest)"] = ["Partial:Stolen Hearts"],
    questDic["Between a Rock..."] = ["Dwarf Cannon", "Fishing Contest"],
    questDic["Big Chompy Bird Hunting"] = [],
    questDic["Biohazard"] = ["Plague City"],
    questDic["Birthright of the Dwarves"] = ["King of the Dwarves"],
    questDic["Follows:Birthright of the Dwarves"] = ["The Fremennik Isles", "Watchtower"],
    questDic["Black Knights' Fortress (quest)"] = ["Misc:13 quest points"],
    questDic["The Blood Pact"] = [],
    questDic["Blood Runs Deep"] = ["Horror from the Deep", "Dream Mentor", "Glorious Memories",
                                   "Misc:Completed easy, medium, and hard Fremennik achievements"],
    questDic["Boric's Task I (miniquest)"] = ["What's Mine is Yours"],
    questDic["Boric's Task II (miniquest)"] = ["Boric's Task I (miniquest)"],
    questDic["Boric's Task III (miniquest)"] = ["Boric's Task II (miniquest)"],
    questDic["The Branches of Darkmeyer"] = ["Legacy of Seergaze", "Legends' Quest"],
    questDic["Bringing Home the Bacon"] = [],
    questDic["The Brink of Extinction"] = ["The Elder Kiln"],
    questDic["Broken Home"] = [],
    questDic["Buyers and Cellars"] = [],
    questDic["Cabin Fever"] = ["Pirate's Treasure", "Rum Deal"],
    questDic["Call of the Ancestors"] = [],
    questDic["Carnillean Rising"] = ["The Blood Pact", "Hazeel Cult", "Misc:50 quest points"],
    questDic["Catapult Construction"] = ["Regicide"],
    questDic["Chef's Assistant"] = ["Cook's Assistant"],
    questDic["Children of Mah"] = ["Fate of the Gods", "The Light Within", "Dishonour among Thieves"],
    questDic["Follows:Children of Mah"] = ["Koschei's Troubles (miniquest)", "Ritual of the Mahjarrat"],
    questDic["The Chosen Commander"] = ["Land of the Goblins"],
    questDic["City of Senntisten"] = ["Battle of the Monolith"],
    questDic["Follows:City of Senntisten"] = ["Desert Treasure", "The Temple at Senntisten"],
    questDic["Civil War I (miniquest)"] = ["Daughter of Chaos"],
    questDic["Civil War II (miniquest)"] = ["Civil War I (miniquest)"],
    questDic["Civil War III (miniquest)"] = ["Civil War II (miniquest)"],
    questDic["Clock Tower"] = [],
    questDic["A Clockwork Syringe"] = ["Rocking Out"],
    questDic["Cold War"] = [],
    questDic["Contact!"] = ["Icthlarin's Little Helper"],
    questDic["Cook's Assistant"] = [],
    questDic["Creature of Fenkenstrain"] = ["The Restless Ghost", "Priest in Peril", "Misc:Ability to enter Morytania"],
    questDic["Crocodile Tears"] = ["The Jack of Spades", "Spirits of the Elid", "Missing My Mummy", "Dealing with Scabaras",
                                   "Misc:Achieve rank 3 overall Menaphos reputation", "Misc:Bring Leela to Senliten's tomb",
                                   "Misc:Fully restore Senliten from the 'Missing My Mummy' quest"],
    questDic["The Curse of Arrav"] = ["The Tale of the Muspah", "Missing My Mummy", "Defender of Varrock", "Troll Romance",
                                      "Shades of Mort'ton",
                                      "Misc:Fully restore Senliten from the 'Missing My Mummy' quest"],
    questDic["Curse of the Black Stone"] = ["Impressing the Locals"],
    questDic["Follows:Curse of the Black Stone"] = ["Sliske's Endgame", "Pieces of Hate"],
    questDic["The Curse of Zaros (miniquest)"] = ["The Restless Ghost", "Partial:Desert Treasure"],
    questDic["Damage Control (miniquest)"] = ["Impressing the Locals", "Harbinger (miniquest)"],
    questDic["The Darkness of Hallowvale"] = ["In Aid of the Myreque"],
    questDic["Daughter of Chaos"] = [],
    questDic["Dead and Buried"] = ["Unwelcome Guests"],
    questDic["Deadliest Catch"] = ["Tower of Life"],
    questDic["Dealing with Scabaras"] = ["The Feud", "Contact!", "Zogre Flesh Eaters"],
    questDic["The Death of Chivalry"] = [],
    questDic["Death Plateau"] = [],
    questDic["Death to the Dorgeshuun"] = ["The Lost Tribe"],
    questDic["Deathcon II"] = [],
    questDic["Defender of Varrock"] = ["Shield of Arrav", "The Knight's Sword", "Demon Slayer", "Temple of Ikov",
                                       "Family Crest", "What Lies Below", "Garden of Tranquillity",
                                       "Misc:Claim Kudos from Historian Minas in Varrock Museum for completing Shield of Arrav"],
    questDic["Demon Slayer"] = [],
    questDic["Desert Slayer Dungeon (miniquest)"] = ["Smoking Kills"],
    questDic["Desert Treasure"] = ["The Dig Site", "The Tourist Trap", "Temple of Ikov", "Priest in Peril",
                                   "Waterfall Quest", "Troll Stronghold"],
    questDic["Desperate Creatures"] = ["Desperate Measures"],
    questDic["Desperate Measures"] = ["Desperate Times",
                                      "Misc:Complete the Anachronia base camp|base camp tutorial on Anachronia"],
    questDic["Follows:Desperate Measures"] = ["Sliske's Endgame", "Curse of the Black Stone", "Fate of the Gods"],
    questDic["Desperate Times"] = ["The Needle Skips", "You Are It"],
    questDic["Follows:Desperate Times"] = ["Sliske's Endgame", "Curse of the Black Stone"],
    questDic["Devious Minds"] = ["Troll Stronghold", "Wanted!", "What's Mine is Yours", "Misc:Ability to enter Morytania"],
    questDic["Diamond in the Rough"] = ["Stolen Hearts"],
    questDic["The Dig Site"] = [],
    questDic["Dimension of Disaster"] = [],
    questDic["Dimension of Disaster: Coin of the Realm"] = [],
    questDic["Dimension of Disaster: Curse of Arrav"] = ["Dimension of Disaster: Coin of the Realm",
                                                         "Dimension of Disaster: Shield of Arrav",
                                                         "Dimension of Disaster: Demon Slayer",
                                                         "Dimension of Disaster: Defender of Varrock",
                                                         "The Curse of Arrav"],
    questDic["Dimension of Disaster: Defender of Varrock"] = ["Dimension of Disaster: Coin of the Realm",
                                                              "Defender of Varrock"],
    questDic["Dimension of Disaster: Demon Slayer"] = ["Dimension of Disaster: Coin of the Realm", "Demon Slayer",
                                                       "Shadow of the Storm"],
    questDic["Dimension of Disaster: Shield of Arrav"] = ["Dimension of Disaster: Coin of the Realm", "Shield of Arrav"],
    questDic["Dishonour among Thieves"] = ["Hazeel Cult", "Missing, Presumed Death", "Misc:Ability to enter Morytania"],
    questDic["Follows:Dishonour among Thieves"] = ["Nomad's Requiem", "Nadir (saga)"],
    questDic["Do No Evil"] = ["Animal Magnetism", "Shadow of the Storm", "Desert Treasure", "Smoking Kills",
                              "Missing My Mummy", "Dealing with Scabaras", "Recipe for Disaster: Freeing King Awowogei",
                              "Misc:Fully restore Senliten from the 'Missing My Mummy' quest",
                              "Misc:Bring Leela to Senliten's tomb"],
    questDic["Doric's Quest"] = [],
    questDic["Doric's Task I (miniquest)"] = ["What's Mine is Yours"],
    questDic["Doric's Task II (miniquest)"] = ["Doric's Task I (miniquest)", "Death Plateau"],
    questDic["Doric's Task III (miniquest)"] = ["Doric's Task II (miniquest)"],
    questDic["Doric's Task IV (miniquest)"] = ["Doric's Task III (miniquest)"],
    questDic["Doric's Task V (miniquest)"] = ["Doric's Task IV (miniquest)"],
    questDic["Doric's Task VI (miniquest)"] = ["Doric's Task V (miniquest)"],
    questDic["Doric's Task VII (miniquest)"] = ["Doric's Task VI (miniquest)"],
    questDic["Doric's Task VIII (miniquest)"] = ["Doric's Task VII (miniquest)"],
    questDic["Dragon Slayer"] = ["Misc:33 quest points"],
    questDic["Dream Mentor"] = ["Eadgar's Ruse", "Lunar Diplomacy"],
    questDic["Druidic Ritual"] = [],
    questDic["Dwarf Cannon"] = [],
    questDic["Eadgar's Ruse"] = ["Troll Stronghold", "Druidic Ritual",
                                 "Misc:Rescue Eadgar|Mad Eadgar from the Troll Stronghold (area)|Troll Stronghold"],
    questDic["Eagles' Peak"] = [],
    questDic["The Elder Kiln"] = [],
    questDic["Elemental Workshop I"] = [],
    questDic["Elemental Workshop II"] = ["Elemental Workshop I"],
    questDic["Elemental Workshop III"] = ["Elemental Workshop II"],
    questDic["Elemental Workshop IV"] = ["Elemental Workshop III"],
    questDic["Enakhra's Lament"] = [],
    questDic["Enchanted key (lore activity)"] = ["Making History", "Meeting History"],
    questDic["Enlightened Journey"] = ["Misc:21 quest points"],
    questDic["Enter the Abyss (miniquest)"] = ["Rune Mysteries"],
    questDic["Ernest the Chicken"] = [],
    questDic["Evil Dave's Big Day Out"] = ["Recipe for Disaster: Freeing Evil Dave"],
    questDic["Follows:Evil Dave's Big Day Out"] = ["Dishonour among Thieves"],
    questDic["Extinction"] = ["Sins of the Father", "Eye of Het II"],
    questDic["Follows:Extinction"] = ["Sliske's Endgame", "One of a Kind", "Children of Mah"],
    questDic["Eye for an Eye (miniquest)"] = ["Impressing the Locals", "Jed Hunter (miniquest)",
                                              "Misc:Discover the island of Cyclosis in player-owned port"],
    questDic["Eye of Het I"] = ["City of Senntisten"],
    questDic["Eye of Het II"] = ["Eye of Het I"],
    questDic["The Eyes of Glouphrie"] = ["The Grand Tree"],
    questDic["A Fairy Tale I - Growing Pains"] = ["Lost City", "Nature Spirit"],
    questDic["A Fairy Tale II - Cure a Queen"] = ["A Fairy Tale I - Growing Pains"],
    questDic["A Fairy Tale III - Battle at Ork's Rift"] = ["A Fairy Tale II - Cure a Queen"],
    questDic["Family Crest"] = [],
    questDic["Fate of the Gods"] = ["Missing, Presumed Death"],
    questDic["Follows:Fate of the Gods"] = ["The World Wakes", "Ritual of the Mahjarrat", "The Temple at Senntisten",
                                            "The Firemaker's Curse"],
    questDic["Full:Fate of the Gods"] = ["The World Wakes", "Ritual of the Mahjarrat", "The Temple at Senntisten",
                                         "Mahjarrat Memories (miniquest)", "The General's Shadow (miniquest)"],
    questDic["Father and Son (miniquest)"] = [],
    questDic["The Feud"] = [],
    questDic["Fight Arena"] = [],
    questDic["Final Destination (miniquest)"] = ["Impressing the Locals", "Tuai Leit's Own (miniquest)",
                                                 "Ghosts from the Past (miniquest)", "Damage Control (miniquest)"],
    questDic["The Firemaker's Curse"] = [],
    questDic["Fishing Contest"] = [],
    questDic["Flag Fall (miniquest)"] = ["Impressing the Locals"],
    questDic["Forgettable Tale of a Drunken Dwarf"] = ["The Giant Dwarf", "Fishing Contest"],
    questDic["Forgiveness of a Chaos Dwarf"] = ["Forgettable Tale of a Drunken Dwarf", "Between a Rock..."],
    questDic["The Fremennik Isles"] = ["The Fremennik Trials"],
    questDic["The Fremennik Trials"] = [],
    questDic["From Tiny Acorns (miniquest)"] = ["Buyers and Cellars"],
    questDic["Fur 'n Seek"] = ["Rag and Bone Man"],
    questDic["Fur 'n Seek/Wish list"] = ["Fur 'n Seek", "Partial:Monkey Madness",
                                         "Misc:Started the pyre ship section of Barbarian Firemaking"],
    questDic["The G-Nome Project"] = [],
    questDic["Garden of Tranquillity"] = ["Creature of Fenkenstrain"],
    questDic["The General's Shadow (miniquest)"] = ["The Curse of Zaros (miniquest)", "Fight Arena"],
    questDic["Gertrude's Cat"] = [],
    questDic["Ghost Stories of Gielinor"] = [],
    questDic["Ghosts Ahoy"] = ["The Restless Ghost", "Priest in Peril", "Misc:Ability to enter Morytania"],
    questDic["Ghosts from the Past (miniquest)"] = ["Impressing the Locals", "Harbinger (miniquest)"],
    questDic["The Giant Dwarf"] = [],
    questDic["Glorious Memories"] = ["Mountain Daughter", "The Fremennik Isles", "Royal Trouble"],
    questDic["Full:Glorious Memories"] = ["Partial:Lunar Diplomacy"],
    questDic["Goblin Diplomacy"] = [],
    questDic["The Golem"] = [],
    questDic["Gower Quest"] = ["Misc:34 quest points"],
    questDic["The Grand Tree"] = [],
    questDic["The Great Brain Robbery"] = ["Creature of Fenkenstrain", "Cabin Fever",
                                           "Recipe for Disaster: Freeing Pirate Pete"],
    questDic["Grim Tales"] = ["Witch's House"],
    questDic["A Guild of Our Own (miniquest)"] = ["Lost Her Marbles (miniquest)", "Partial:The Feud"],
    questDic["Guilded Eggstravaganza"] = ["Misc:A high tolerance for puns"],
    questDic["Gunnar's Ground"] = [],
    questDic["The Hand in the Sand"] = [],
    questDic["Harbinger (miniquest)"] = ["Impressing the Locals", "Eye for an Eye (miniquest)"],
    questDic["Haunted Mine"] = ["Priest in Peril", "Misc:Ability to enter Morytania"],
    questDic["Hawthorn"] = [],
    questDic["Hazeel Cult"] = [],
    questDic["Head of the Family (miniquest)"] = ["Impressing the Locals"],
    questDic["Heart of Stone"] = ["Carnillean Rising", "Rune Memories"],
    questDic["Follows:Heart of Stone"] = ["Rune Mechanics", "The Elder Kiln", "Fate of the Gods"],
    questDic["Heartstealer"] = [],
    questDic["Helping Laniakea (miniquest)"] = [],
    questDic["Hero's Welcome"] = ["Lunar Diplomacy", "Tai Bwo Wannai Trio", "Misc:Master Barbarian Training"],
    questDic["Follows:Hero's Welcome"] = ["One of a Kind", "Ritual of the Mahjarrat"],
    questDic["Heroes' Quest"] = ["Shield of Arrav", "Dragon Slayer", "Druidic Ritual", "Lost City", "Merlin's Crystal",
                                 "Misc:56 quest points"],
    questDic["Holly"] = [],
    questDic["Holy Grail"] = ["Merlin's Crystal"],
    questDic["Hopespear's Will (miniquest)"] = ["Land of the Goblins", "A Fairy Tale I - Growing Pains",
                                                "Misc:Access to the fairy ring network", "Partial: Desert Treasure"],
    questDic["Horror from the Deep"] = ["Bar Crawl (miniquest)"],
    questDic["Hunt for Red Raktuber"] = ["Cold War", "Sea Slug"],
    questDic["The Hunt for Surok (miniquest)"] = ["What Lies Below"],
    questDic["Icthlarin's Little Helper"] = ["Gertrude's Cat", "Diamond in the Rough"],
    questDic["Imp Catcher"] = [],
    questDic["Impressing the Locals"] = [],
    questDic["In Aid of the Myreque"] = ["In Search of the Myreque"],
    questDic["Follows:In Aid of the Myreque"] = ["Shades of Mort'ton"],
    questDic["In Memory of the Myreque (miniquest)"] = ["The Lord of Vampyrium"],
    questDic["In Pyre Need"] = [],
    questDic["In Search of the Myreque"] = ["Nature Spirit"],
    questDic["The Jack of Spades"] = ["Diamond in the Rough"],
    questDic["Jed Hunter (miniquest)"] = ["Impressing the Locals", "Flag Fall (miniquest)",
                                          "Head of the Family (miniquest)", "Spiritual Enlightenment (miniquest)"],
    questDic["Follows:Jed Hunter (miniquest)"] = ["Deadliest Catch"],
    questDic["Jungle Potion"] = [],
    questDic["Kennith's Concerns"] = ["The Slug Menace"],
    questDic["Kili Row"] = ["Necromancy!", "Misc:Collect a set of Deathwarden robes|necromancer robes from Sostratus"],
    questDic["Kindred Spirits"] = ["Missing, Presumed Death"],
    questDic["Follows:Kindred Spirits"] = ["Deadliest Catch"],
    questDic["King of the Dwarves"] = ["Forgiveness of a Chaos Dwarf", "My Arm's Big Adventure"],
    questDic["King's Ransom"] = ["Holy Grail", "Murder Mystery", "One Small Favour"],
    questDic["The Knight's Sword"] = [],
    questDic["Koschei's Troubles (miniquest)"] = ["Blood Runs Deep", "Ritual of the Mahjarrat"],
    questDic["Lair of Tarn Razorlor (miniquest)"] = ["Haunted Mine"],
    questDic["Land of the Goblins"] = ["Another Slice of H.A.M.", "Fishing Contest"],
    questDic["Learning the Ropes"] = [],
    questDic["Legacy of Seergaze"] = ["The Darkness of Hallowvale"],
    questDic["Follows:Legacy of Seergaze"] = ["Shades of Mort'ton"],
    questDic["Legends' Quest"] = ["Heroes' Quest", "Family Crest", "Underground Pass", "Waterfall Quest", "Shilo Village",
                                  "Misc:107 quest points"],
    questDic["Let Them Eat Pie"] = [],
    questDic["The Light Within"] = ["Meeting History", "The Temple at Senntisten", "Plague's End", "The World Wakes",
                                    "Fate of the Gods"],
    questDic["The Lord of Vampyrium"] = ["The Branches of Darkmeyer"],
    questDic["Lost City"] = [],
    questDic["Lost Her Marbles (miniquest)"] = ["From Tiny Acorns (miniquest)"],
    questDic["The Lost Toys (miniquest)"] = ["The Lord of Vampyrium"],
    questDic["The Lost Tribe"] = ["Goblin Diplomacy"],
    questDic["Love Story"] = ["Swan Song", "Recipe for Disaster: Freeing Sir Amik Varze"],
    questDic["Lunar Diplomacy"] = ["The Fremennik Trials", "Lost City", "Shilo Village"],
    questDic["Mahjarrat Memories (miniquest)"] = ["Koschei's Troubles (miniquest)", "Missing, Presumed Death"],
    questDic["Making History"] = ["Priest in Peril", "The Restless Ghost", "Misc:Ability to enter Morytania"],
    questDic["Meeting History"] = ["Making History"],
    questDic["Merlin's Crystal"] = [],
    questDic["The Mighty Fall"] = ["The Chosen Commander", "My Arm's Big Adventure", "Missing, Presumed Death",
                                   "The Hunt for Surok (miniquest)"],
    questDic["Missing My Mummy"] = ["Icthlarin's Little Helper", "The Golem", "Diamond in the Rough"],
    questDic["Full:Missing My Mummy"] = ["Partial:Garden of Tranquillity"],
    questDic["Missing, Presumed Death"] = [],
    questDic["Follows:Missing, Presumed Death"] = ["Koschei's Troubles (miniquest)", "The Chosen Commander",
                                                   "Ritual of the Mahjarrat", "The World Wakes", "The Death of Chivalry"],
    questDic["Mogre (lore activity)"] = [],
    questDic["Monk's Friend"] = [],
    questDic["Monkey Madness"] = ["The Grand Tree", "Tree Gnome Village"],
    questDic["Mountain Daughter"] = [],
    questDic["Mourning's End Part I"] = ["Roving Elves", "Sheep Herder", "Big Chompy Bird Hunting"],
    questDic["Mourning's End Part II"] = ["Mourning's End Part I"],
    questDic["Murder Mystery"] = [],
    questDic["Murder on the Border"] = ["New Foundations",
                                        "Misc:Must have built Town Hall (Fort Forinthry)|Town Hall (Tier 1)",
                                        "Misc:Must have built Command Centre|Command Centre (Tier 1)",
                                        "Misc:Must have built Workshop (Fort Forinthry)|Workshop (Tier 1)",
                                        "Misc:Must have built Chapel (Fort Forinthry)|Chapel (Tier 1)"],
    questDic["My Arm's Big Adventure"] = ["Eadgar's Ruse", "The Feud", "Jungle Potion",
                                          "Misc:Work on the Tai Bwo Wannai Cleanup"],
    questDic["Myths of the White Lands"] = [],
    questDic["Nadir (saga)"] = ["Misc:Find and free Skaldrun from the frozen floors in Daemonheim"],
    questDic["Follows:Nadir (saga)"] = ["Ritual of the Mahjarrat"],
    questDic["Nature Spirit"] = ["Priest in Peril", "The Restless Ghost", "Misc:Ability to enter Morytania"],
    questDic["Necromancy!"] = [],
    questDic["The Needle Skips"] = [],
    questDic["New Foundations"] = [],
    questDic["Nomad's Elegy"] = ["Dishonour among Thieves", "Nomad's Requiem", "Heart of Stone", "The Mighty Fall",
                                 "Throne of Miscellania", "The Void Stares Back"],
    questDic["Follows:Nomad's Elegy"] = ["While Guthix Sleeps", "Blood Runs Deep"],
    questDic["Nomad's Requiem"] = ["King's Ransom",
                                   "Misc:Complete the Knight Waves training ground|Knight Waves in Camelot",
                                   "Misc:Complete the Soul Wars tutorial"],
    questDic["O Little Town of Daemonheim"] = [],
    questDic["Observatory Quest"] = [],
    questDic["Olaf's Quest"] = ["The Fremennik Trials"],
    questDic["Once Upon a Slime"] = [],
    questDic["Once Upon a Time in Gielinor"] = [],
    questDic["Once Upon a Time in Gielinor: Finale"] = ["Once Upon a Time in Gielinor: Fortunes"],
    questDic["Follows:Once Upon a Time in Gielinor: Finale"] = ["The Death of Chivalry", "Carnillean Rising",
                                                                "Impressing the Locals"],
    questDic["Once Upon a Time in Gielinor: Flashback"] = ["Once Upon a Time in Gielinor: Foreshadowing"],
    questDic["Follows:Once Upon a Time in Gielinor: Flashback"] = ["Merlin's Crystal", "Animal Magnetism",
                                                                   "Diamond in the Rough"],
    questDic["Once Upon a Time in Gielinor: Foreshadowing"] = [],
    questDic["Follows:Once Upon a Time in Gielinor: Foreshadowing"] = ["Demon Slayer", "Dragon Slayer", "Vampyre Slayer"],
    questDic["Once Upon a Time in Gielinor: Fortunes"] = ["Once Upon a Time in Gielinor: Flashback"],
    questDic["Follows:Once Upon a Time in Gielinor: Fortunes"] = ["Missing, Presumed Death", "Dishonour among Thieves",
                                                                  "The Death of Chivalry"],
    questDic["One Foot in the Grave (miniquest)"] = ["The Hand in the Sand", "Partial:Back to my Roots"],
    questDic["One of a Kind"] = ["A Tail of Two Cats", "King's Ransom", "The World Wakes", "Missing, Presumed Death"],
    questDic["Follows:One of a Kind"] = ["Ritual of the Mahjarrat"],
    questDic["One Piercing Note"] = [],
    questDic["One Small Favour"] = ["Rune Mysteries", "Shilo Village", "Druidic Ritual"],
    questDic["Our Man in the North"] = ["Do No Evil", "Crocodile Tears", "Misc:Achieve rank 6 overall Menaphos reputation"],
    questDic["Partying is Such Sweet Sorrow"] = [],
    questDic["The Path of Glouphrie"] = ["The Eyes of Glouphrie", "Tree Gnome Village", "Waterfall Quest"],
    questDic["Perils of Ice Mountain"] = [],
    questDic["Philipe's Big Adventure"] = [],
    questDic["'Phite Club"] = ["Our Man in the North", "Misc:Achieve rank 9 overall Menaphos reputation"],
    questDic["Pieces of Hate"] = ["A Clockwork Syringe", "Gertrude's Cat"],
    questDic["Pirate's Treasure"] = [],
    questDic["Plague City"] = [],
    questDic["Plague's End"] = ["Within the Light", "Catapult Construction", "Making History"],
    questDic["Priest in Peril"] = [],
    questDic["Prince Ali Rescue"] = [],
    questDic["The Prisoner of Glouphrie"] = ["The Path of Glouphrie", "Roving Elves"],
    questDic["Purple Cat (miniquest)"] = ["Swept Away", "Gertrude's Cat"],
    questDic["Quiet Before the Swarm"] = ["Imp Catcher", "Wanted!"],
    questDic["Follows:Quiet Before the Swarm"] = ["Misc:Pest Control minigame"],
    questDic["Rag and Bone Man"] = [],
    questDic["Rag and Bone Man/Wish list"] = ["Rag and Bone Man", "Mogre (lore activity)", "Partial:Zogre Flesh Eaters",
                                              "Partial:Creature of Fenkenstrain"],
    questDic["Raksha, the Shadow Colossus (quest)"] = [],
    questDic["Rat Catchers"] = ["Icthlarin's Little Helper"],
    questDic["Rebuilding Edgeville (miniquest)"] = ["Ritual of the Mahjarrat"],
    questDic["Recipe for Disaster"] = ["Cook's Assistant", "Big Chompy Bird Hunting", "Biohazard", "Demon Slayer",
                                       "Desert Treasure", "Fishing Contest", "Gertrude's Cat", "Goblin Diplomacy",
                                       "Horror from the Deep", "Partial:Legends' Quest", "Lost City", "Monkey Madness",
                                       "Murder Mystery", "Nature Spirit", "Priest in Peril", "The Restless Ghost",
                                       "Shadow of the Storm", "Witch's House", "Misc:176 quest points"],
    questDic["Recipe for Disaster: Another Cook's Quest"] = ["Cook's Assistant"],
    questDic["Recipe for Disaster: Defeating the Culinaromancer"] = ["Recipe for Disaster: Another Cook's Quest",
                                                                     "Recipe for Disaster: Freeing the Mountain Dwarf",
                                                                     "Recipe for Disaster: Freeing the Goblin Generals",
                                                                     "Recipe for Disaster: Freeing Pirate Pete",
                                                                     "Recipe for Disaster: Freeing the Lumbridge Sage",
                                                                     "Recipe for Disaster: Freeing Evil Dave",
                                                                     "Recipe for Disaster: Freeing Skrach Uglogwee",
                                                                     "Recipe for Disaster: Freeing Sir Amik Varze",
                                                                     "Recipe for Disaster: Freeing King Awowogei",
                                                                     "Desert Treasure", "Horror from the Deep",
                                                                     "Misc:176 quest points"],
    questDic["Recipe for Disaster: Freeing Evil Dave"] = ["Recipe for Disaster: Another Cook's Quest", "Gertrude's Cat",
                                                          "Shadow of the Storm"],
    questDic["Recipe for Disaster: Freeing King Awowogei"] = ["Recipe for Disaster: Another Cook's Quest",
                                                              "Monkey Madness"],
    questDic["Recipe for Disaster: Freeing Pirate Pete"] = ["Recipe for Disaster: Another Cook's Quest"],
    questDic["Recipe for Disaster: Freeing Sir Amik Varze"] = ["Recipe for Disaster: Another Cook's Quest", "Lost City",
                                                               "Partial:Legends' Quest"],
    questDic["Recipe for Disaster: Freeing Skrach Uglogwee"] = ["Recipe for Disaster: Another Cook's Quest",
                                                                "Big Chompy Bird Hunting"],
    questDic["Recipe for Disaster: Freeing the Goblin Generals"] = ["Recipe for Disaster: Another Cook's Quest",
                                                                    "Goblin Diplomacy"],
    questDic["Recipe for Disaster: Freeing the Lumbridge Sage"] = ["Recipe for Disaster: Another Cook's Quest",
                                                                   "Big Chompy Bird Hunting", "Biohazard", "Demon Slayer",
                                                                   "Murder Mystery", "Nature Spirit", "Priest in Peril",
                                                                   "Witch's House", "The Restless Ghost"],
    questDic["Recipe for Disaster: Freeing the Mountain Dwarf"] = ["Recipe for Disaster: Another Cook's Quest",
                                                                   "Fishing Contest"],
    questDic["Recruitment Drive"] = [],
    questDic["Regicide"] = ["Underground Pass"],
    questDic["Remains of the Necrolord"] = ["Tomes of the Warlock", "Vengeance (saga)", "Nadir (saga)"],
    questDic["The Restless Ghost"] = [],
    questDic["Ritual of the Mahjarrat"] = ["The Temple at Senntisten", "While Guthix Sleeps", "Hazeel Cult",
                                           "Enakhra's Lament", "The Slug Menace", "A Fairy Tale III - Battle at Ork's Rift",
                                           "Rocking Out", "A Tail of Two Cats", "Fight Arena"],
    questDic["Follows:Ritual of the Mahjarrat"] = ["The General's Shadow (miniquest)"],
    questDic["River of Blood"] = ["The Lord of Vampyrium", "Defender of Varrock", "All Fired Up"],
    questDic["Rocking Out"] = ["The Great Brain Robbery"],
    questDic["Romeo and Juliet"] = [],
    questDic["Roving Elves"] = ["Regicide", "Waterfall Quest"],
    questDic["Royal Trouble"] = ["Throne of Miscellania"],
    questDic["Rum Deal"] = ["Zogre Flesh Eaters", "Priest in Peril", "Misc:Ability to enter Morytania"],
    questDic["Rune Mechanics"] = [],
    questDic["Rune Memories"] = ["Rune Mysteries"],
    questDic["Rune Mysteries"] = [],
    questDic["Rune Mythos"] = ["Necromancy!"],
    questDic["Salt in the Wound"] = ["Kennith's Concerns"],
    questDic["Scorpion Catcher"] = ["Bar Crawl (miniquest)"],
    questDic["Sea Slug"] = [],
    questDic["Shades of Mort'ton"] = ["Misc:Ability to enter Morytania"],
    questDic["Shadow of the Storm"] = ["Demon Slayer", "The Golem"],
    questDic["A Shadow over Ashdale"] = [],
    questDic["Sheep Herder"] = [],
    questDic["Sheep Shearer (miniquest)"] = [],
    questDic["Shield of Arrav"] = [],
    questDic["Shilo Village"] = ["Jungle Potion"],
    questDic["Sins of the Father"] = ["Desperate Measures"],
    questDic["Sliske's Endgame"] = ["The Death of Chivalry", "One of a Kind", "Nomad's Elegy", "Kindred Spirits",
                                    "Hero's Welcome", "Children of Mah"],
    questDic["The Slug Menace"] = ["Sea Slug", "Wanted!"],
    questDic["Smoking Kills"] = ["The Restless Ghost", "Icthlarin's Little Helper"],
    questDic["Some Like It Cold"] = ["Hunt for Red Raktuber"],
    questDic["Song from the Depths"] = [],
    questDic["A Soul's Bane"] = [],
    questDic["Spirit of Summer"] = ["The Restless Ghost"],
    questDic["The Spirit of War"] = ["Vessel of the Harbinger", "Misc:3,000 City of Um vessel souls"],
    questDic["Full:The Spirit of War"] = ["Kili Row"],
    questDic["Spirits of the Elid"] = [],
    questDic["Spiritual Enlightenment (miniquest)"] = ["Impressing the Locals",
                                                       "Misc:Complete the 'Meet the Assassin' voyage in player-owned port"],
    questDic["Stolen Hearts"] = [],
    questDic["A Stray in a Manger"] = [],
    questDic["Succession"] = ["Civil War III (miniquest)", "Misc:Unlock Infernal Puzzle Box Tier 5"],
    questDic["Summer's End"] = ["Spirit of Summer"],
    questDic["Swan Song"] = ["One Small Favour", "Garden of Tranquillity", "Misc:101 quest points"],
    questDic["Swept Away"] = [],
    questDic["Tai Bwo Wannai Trio"] = ["Jungle Potion"],
    questDic["A Tail of Two Cats"] = ["Icthlarin's Little Helper", "Gertrude's Cat"],
    questDic["The Tale of the Muspah"] = [],
    questDic["Tales of Nomad (miniquest)"] = ["Nomad's Elegy"],
    questDic["Tales of the God Wars (miniquest)"] = ["Misc:Ability to enter Morytania",
                                                     "Misc:Access to the God Wars Dungeon"],
    questDic["Tears of Guthix"] = ["Misc:44 quest points"],
    questDic["The Temple at Senntisten"] = ["Devious Minds", "Desert Treasure", "The Curse of Arrav", "Misc:125 Kudos"],
    questDic["Temple of Ikov"] = [],
    questDic["That Old Black Magic"] = ["Necromancy!", "The Blood Pact"],
    questDic["Full:That Old Black Magic"] = ["The Spirit of War"],
    questDic["Thok It To 'Em (saga)"] = ["Misc:Find and free Skaldrun from the frozen floors in Daemonheim"],
    questDic["Thok Your Block Off (saga)"] = ["Misc:Find and free Skaldrun from the frozen floors in Daemonheim"],
    questDic["Three's Company (saga)"] = ["Misc:Find and free Skaldrun from the frozen floors in Daemonheim"],
    questDic["Throne of Miscellania"] = ["The Fremennik Trials", "Heroes' Quest"],
    questDic["TokTz-Ket-Dill"] = [],
    questDic["Tomes of the Warlock"] = ["The Spirit of War", "The Jack of Spades"],
    questDic["Tortle Combat (miniquest)"] = ["Misc:Complete the player-owned farm tutorial"],
    questDic["The Tourist Trap"] = [],
    questDic["Tower of Life"] = [],
    questDic["A Towering Feast"] = [],
    questDic["Tree Gnome Village"] = [],
    questDic["Tribal Totem"] = [],
    questDic["Troll Romance"] = ["Troll Stronghold"],
    questDic["Troll Stronghold"] = ["Death Plateau"],
    questDic["Tuai Leit's Own (miniquest)"] = ["Impressing the Locals", "Harbinger (miniquest)"],
    questDic["Turkey Protest"] = [],
    questDic["Tutorial"] = [],
    questDic["Twilight of the Gods"] = ["Extinction", "Broken Home", "Misc:Complete the Eyes in Their Stars mystery",
                                        "Misc:Meet Naressa in Senntisten"],
    questDic["Underground Pass"] = ["Biohazard"],
    questDic["Unstable Foundations"] = [],
    questDic["Unwelcome Guests"] = ["Murder on the Border"],
    questDic["Vampyre Slayer"] = [],
    questDic["The Vault of Shadows"] = ["Misc:Ability to see the Shadow Realm inside Kharid-et"],
    questDic["Vengeance (saga)"] = ["Misc:Find and free Skaldrun from the frozen floors in Daemonheim"],
    questDic["Vessel of the Harbinger"] = ["Rune Mythos", "Ghosts Ahoy"],
    questDic["Violet is Blue"] = [],
    questDic["Violet is Blue Too"] = ["Violet is Blue"],
    questDic["A Void Dance"] = ["Quiet Before the Swarm"],
    questDic["The Void Stares Back"] = ["A Void Dance"],
    questDic["Follows:The Void Stares Back"] = ["Misc:Conquest tutorial"],
    questDic["Wandering Ga'al (miniquest)"] = ["The Brink of Extinction", "Partial:Desert Treasure"],
    questDic["Wanted!"] = ["The Lost Tribe", "Priest in Peril", "Recruitment Drive", "Enter the Abyss (miniquest)",
                           "Misc:33 quest points"],
    questDic["Watchtower"] = [],
    questDic["Waterfall Quest"] = [],
    questDic["What Lies Below"] = [],
    questDic["What's Mine is Yours"] = [],
    questDic["While Guthix Sleeps"] = ["Defender of Varrock", "Dream Mentor", "The Hand in the Sand", "King's Ransom",
                                       "Legends' Quest", "The Path of Glouphrie", "Tears of Guthix", "Wanted!",
                                       "The Hunt for Surok (miniquest)", "Misc:Ability to enter the Warriors' Guild"],
    questDic["Follows:While Guthix Sleeps"] = ["Nature Spirit"],
    questDic["Witch's House"] = [],
    questDic["Witch's Potion (miniquest)"] = [],
    questDic["Within the Light"] = ["Mourning's End Part II"],
    questDic["Wolf Whistle"] = [],
    questDic["The World Wakes"] = [],
    questDic["Full:The World Wakes"] = ["Ritual of the Mahjarrat", "The Firemaker's Curse", "The Branches of Darkmeyer",
                                        "The Void Stares Back", "The Chosen Commander"],
    questDic["You Are It"] = [],
    questDic["Zogre Flesh Eaters"] = ["Big Chompy Bird Hunting", "Jungle Potion"],
    return questDic
